INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Gianluigi', 'Buffon', 40, 'Paris Saint Germain', 'goalkeeper', 2, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Manuel', 'Neuer', 32, 'Bayern Munchen', 'goalkeeper', 35, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Keylor', 'Navas', 31, 'Real Madrid', 'goalkeeper', 18, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Joao', 'Cancelo', 24, 'Juventus', 'right back', 35, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Dani', 'Alves', 35, 'Paris Saint Germain', 'right back', 4, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Sergio', 'Ramos', 32, 'Real Madrid', 'central defender', 45, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Giorgio', 'Chiellini', 33, 'Juventus', 'central defender', 10, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Mats', 'Hummels', 29, 'Bayern Munchen', 'central defender', 60, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Diego', 'Godín', 32, 'Atletico de Madrid', 'central defender', 35, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Marcelo', 'Da Silva', 30, 'Real Madrid', 'left back', 60, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Alex', 'Sandro', 27, 'Juventus', 'left back', 45, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Kevin', 'De Bruyne', 27, 'Manchester City', 'offensive midfielder', 150, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Paulo', 'Dybala', 24, 'Juventus', 'offensive midfielder', 110, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Arturo', 'Vidal', 31, 'Bayern Munchen', 'defensive midfielder', 35, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Sergio', 'Busquets', 30, 'FC Barcelona', 'defensive midfielder', 80, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Toni', 'Kroos', 28, 'Real Madrid', 'central midfielder', 80, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Luka', 'Modric', 32, 'Real Madrid', 'central midfielder', 25, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Luis', 'Suarez', 31, 'FC Barcelona', 'striker', 70, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Robert', 'Lewandowski', 29, 'Bayern Munchen', 'striker', 85, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Gonzalo', 'Higuaín', 30, 'Juventus', 'striker', 55, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Sergio', 'Aguero', 30, 'Manchester City', 'striker', 80, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Antoine', 'Griezmann', 27, 'Atletico de Madrid', 'striker', 120, NULL, NULL);
INSERT INTO football_player (name, surname, age, team, position, price, status, lraId) VALUES ('Pierre-Emerick', 'Aubameyang', 29, 'FC Arsenal', 'striker', 75, NULL, NULL);