INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Gianluigi', 'Buffon', 40, 'Paris Saint Germain', 'goalkeeper', 2);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Manuel', 'Neuer', 32, 'Bayern Munchen', 'goalkeeper', 35);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Keylor', 'Navas', 31, 'Real Madrid', 'goalkeeper', 18);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Joao', 'Cancelo', 24, 'Juventus', 'right back', 35);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Dani', 'Alves', 35, 'Paris Saint Germain', 'right back', 4);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Sergio', 'Ramos', 32, 'Real Madrid', 'central defender', 45);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Giorgio', 'Chiellini', 33, 'Juventus', 'central defender', 10);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Mats', 'Hummels', 29, 'Bayern Munchen', 'central defender', 60);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Diego', 'Godín', 32, 'Atletico de Madrid', 'central defender', 35);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Marcelo', 'Da Silva', 30, 'Real Madrid', 'left back', 60);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Alex', 'Sandro', 27, 'Juventus', 'left back', 45);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Kevin', 'De Bruyne', 27, 'Manchester City', 'offensive midfielder', 150);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Paulo', 'Dybala', 24, 'Juventus', 'offensive midfielder', 110);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Arturo', 'Vidal', 31, 'Bayern Munchen', 'defensive midfielder', 35);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Sergio', 'Busquets', 30, 'FC Barcelona', 'defensive midfielder', 80);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Toni', 'Kroos', 28, 'Real Madrid', 'central midfielder', 80);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Luka', 'Modric', 32, 'Real Madrid', 'central midfielder', 25);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Luis', 'Suarez', 31, 'FC Barcelona', 'striker', 70);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Robert', 'Lewandowski', 29, 'Bayern Munchen', 'striker', 85);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Gonzalo', 'Higuaín', 30, 'Juventus', 'striker', 55);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Sergio', 'Aguero', 30, 'Manchester City', 'striker', 80);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Antoine', 'Griezmann', 27, 'Atletico de Madrid', 'striker', 120);
INSERT INTO football_player (name, surname, age, team, position, price) VALUES ('Pierre-Emerick', 'Aubameyang', 29, 'FC Arsenal', 'striker', 75);